-- AlterTable
ALTER TABLE "products" ALTER COLUMN "name_ar" DROP NOT NULL,
ALTER COLUMN "name_ku" DROP NOT NULL,
ALTER COLUMN "unit" DROP NOT NULL,
ALTER COLUMN "image" DROP NOT NULL,
ALTER COLUMN "lotNumber" DROP NOT NULL,
ALTER COLUMN "slug" DROP NOT NULL;
